Implemented argument for compositor to use

diff --git a/startlxqtwayland.in b/startlxqtwayland.in
--- a/startlxqtwayland.in
+++ b/startlxqtwayland.in
@@ -70,14 +70,27 @@ share_dir="$(dirname $(dirname "$0"))"/share
 if [ ! -d "$XDG_CONFIG_HOME/lxqt/wayland" ]; then
     mkdir -p $XDG_CONFIG_HOME/lxqt/wayland/
 fi
-# Check for compositor in user config file and fallback dirs
-for d in $(echo "$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS" | tr : '\n'); do
-    config_file="$d/lxqt/session.conf"
-    [ -f "$config_file" ] && [ -r "$config_file" ] || continue
-    COMPOSITOR="$(sed -nre '/^compositor\s*=/ { s@^[^=]+=\s*(/|\S+.*/)?([^/]+)?$@\2@; p; }' "$config_file")"
-    [ -z "$COMPOSITOR" ] || break
-done
 
+if [ -z "$1" ]
+    then
+    echo "No argument supplied"
+    # Check for compositor in user config file and fallback dirs
+    for d in $(echo "$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS" | tr : '\n'); do
+        config_file="$d/lxqt/session.conf"
+        [ -f "$config_file" ] && [ -r "$config_file" ] || continue
+        COMPOSITOR="$(sed -nre '/^compositor\s*=/ { s@^[^=]+=\s*(/|\S+.*/)?([^/]+)?$@\2@; p; }' "$config_file")"
+        [ -z "$COMPOSITOR" ] || break
+    done
+else
+    #Validity check
+    if ! command -v $1 >&2; then
+        echo "$1 not found, exiting..."
+        exit 0
+    else
+    COMPOSITOR=$1
+    echo "Starting LXQt Wayland Session using $1. This is not persistent."
+    fi
+fi
 export XDG_CURRENT_DESKTOP="LXQt:$COMPOSITOR:wlroots"
 
 valid_layouts=$(grep -A98 '! layout' /usr/share/X11/xkb/rules/base.lst | awk '{print $1}' | grep -v '!')
